const APPLICATION_STATUSES = Object.freeze({
  APPLIED: "APPLIED",
  SHORTLISTED: "SHORTLISTED",
  REJECTED: "REJECTED",
  HIRED: "HIRED",
  WITHDRAWN: "WITHDRAWN",
});

const APPLICATION_STATUS_VALUES = Object.values(APPLICATION_STATUSES);

export { APPLICATION_STATUSES, APPLICATION_STATUS_VALUES };