const INTERVIEW_STATUSES = Object.freeze({
  SCHEDULED: "SCHEDULED",
  CONFIRMED: "CONFIRMED",
  RESCHEDULED: "RESCHEDULED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  DECLINED: "DECLINED",
});

const INTERVIEW_STATUS_VALUES = Object.values(INTERVIEW_STATUSES);

export { INTERVIEW_STATUSES, INTERVIEW_STATUS_VALUES };