const RECRUITER_STATUSES = Object.freeze({
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
});

const RECRUITER_STATUS_VALUES = Object.values(RECRUITER_STATUSES);

export { RECRUITER_STATUSES, RECRUITER_STATUS_VALUES };
